# Copy a TCPS descriptor from Autonomous Database > Database Connection.
app.url=${ADB_JDBC_URL}
app.mode=sdk
app.oci.authentication=config-file
app.oci.configFile=${OCI_CONFIG_FILE}
app.oci.profile=${OCI_PROFILE}
app.oci.scope=${OCI_DB_SCOPE}
