# Copy a TCPS descriptor from Autonomous Database > Database Connection.
app.url=${ADB_JDBC_URL}
app.mode=provider
oracle.jdbc.provider.accessToken=ojdbc-provider-oci-token
oracle.jdbc.provider.accessToken.authenticationMethod=instance-principal
oracle.jdbc.provider.accessToken.scope=${OCI_DB_SCOPE}
